### ISSUE TITLE
Can I get the test data?

### ISSUE THREAD

**Issue by francisfa** [hoffmangroup/2020spikein#1]
Hi, @swils6 

I want to test the glm model using your data, however, I cannot find the bed files such as below.

`S6547 <- read.table("/cluster/projects/hoffmangroup/data_samanthawilson/2020_0.01ng_HCT116/filtered_aligned.trimmed.6547_S3_L_R1_001.fastqtrimmed.6547_S3_L_R2_001.fastq_sorted_dedup_sort.bed")`
`S6547 <- as.data.frame(S6547[,1])`

So, could you provide some bed files [Small file is enough] for me to test? This will help me a lot.

Thanks.

**Comment by swils6** [comment]
The test data has been deposited on GEO and can be downloaded there. Here is the link - https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE166259
